[package]
name = "polkadot-node-core-approvals"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
# futures = "0.3.5"
# futures-timer = "3.0.2"
# log = "0.4.8"
# derive_more = "0.99.9"
derive_more = "0.14.1"

# bitvec = { version = "0.17.4", default-features = false, features = ["alloc"] }
# streamunordered = "0.5.1"

sp-api = { git = "https://github.com/paritytech/substrate", branch = "master" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "master" }
keystore = { package = "sc-keystore", git = "https://github.com/paritytech/substrate", branch = "master" }
primitives = { package = "sp-core", git = "https://github.com/paritytech/substrate", branch = "master" }

polkadot-primitives = { path = "../../../primitives" }
polkadot-node-primitives = { path = "../../primitives" }
polkadot-subsystem = { package = "polkadot-node-subsystem", path = "../../subsystem" }
# statement-table = { package = "polkadot-statement-table", path = "../../../statement-table" }

babe-primitives = { package = "sp-consensus-babe", git = "https://github.com/paritytech/substrate", branch = "master" }
sc-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "master"}
# sc-consensus-slots = { version = "0.8.0-rc3", git = "https://github.com/paritytech/substrate", branch = "master"}
merlin = { version = "2.0", default-features = false }
schnorrkel = { version = "0.9.1", features = ["u64_backend"], default-features = false }

[dev-dependencies]
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "master" }
# futures = { version = "0.3.5", features = ["thread-pool"] }
# subsystem-test = { package = "polkadot-subsystem-test-helpers", path = "../../test-helpers/subsystem" }
# assert_matches = "1.3.0"

[workspace]